POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "name": "Limpar cozinha",
    "description": "limpar a cozinha toda",
    "status": false,
    "subTask": [
        {
            "name": "Lavar a louça",
            "description": "Deixar pratos de molho",
            "status": false
        },
        {
            "name": "Passar pano",
            "description": "Deixar o pano secando do lado de fora",
            "status": false
        }
    ]
}

###
GET http://localhost:3000/api/tasks

###
GET http://localhost:3000/api/tasks/670c1d086c09f150eb7528b6

###
DELETE http://localhost:3000/api/tasks/670c1d086c09f150eb7528b6

###
PUT http://localhost:3000/api/tasks/670af2cc641b3cdfc07063b2
Content-Type: application/json

{
    "name": "Limpar cozinha",
    "description": "limpar a cozinha toda",
    "status": false,
    "subTask": [
        {
            "name": "Lavar a louça",
            "description": "Deixar pratos de molho",
            "status": false,
        },
        {
            "name": "Passar pano",
            "description": "Deixar o pano secando do lado de fora",
            "status": false,
        }
    ]
}