POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "name": "teste delete",
    "description": "fer",
    "status": false
}

###
GET http://localhost:3000/api/tasks

###
GET http://localhost:3000/api/tasks/670c1d086c09f150eb7528b6

###
DELETE http://localhost:3000/api/tasks/670c1d086c09f150eb7528b6

###
PUT http://localhost:3000/api/tasks/670c1ef71505c14399533971
Content-Type: application/json

{
    "name": "Atualizar registro",
    "description": "fernando",
    "status": true
}